"""Authoritative built-in node catalog grouped by editor purpose."""
from __future__ import annotations

from core.nodes.advanced_color_nodes import (ClarityNode, ColorBalanceNode,
                                             LevelsNode, ShadowsHighlightsNode,
                                             VibranceNode)
from core.nodes.audio_nodes import (AudioAdvancedMixerNode, AudioAttachNode,
                                    AudioCompressorNode, AudioDelayNode,
                                    AudioEqNode, AudioExtractNode,
                                    AudioGainNode, AudioGateNode,
                                    AudioLimiterNode, AudioMixNode,
                                    AudioNormalizeNode, AudioPanNode,
                                    AudioReverbNode, AudioStereoWidthNode,
                                    AudioToMonoNode)
from core.nodes.base import Node
from core.nodes.color_effects import (ChannelMixerNode, ExposureContrastNode,
                                      HueSaturationNode, InvertNode,
                                      MonochromeNode, PosterizeNode,
                                      ThresholdNode, WhiteBalanceNode)
from core.nodes.color_grading import ColorGradingNode
from core.nodes.compositing import (AlphaOverNode, AlphaUnderNode,
                                    DissolveNode, MatteCombineProNode,
                                    MergeNode, StencilNode)
from core.nodes.creative_nodes import (ChromaticAberrationNode, DuotoneNode,
                                       GlitchNode, GlowEdgesNode, GlowNode,
                                       HalftoneNode, KaleidoscopeNode,
                                       LensDistortionNode, LightWrapNode,
                                       MirrorNode, NeonGlowNode, PixelSortNode,
                                       PosterEdgesNode, RGBSplitNode,
                                       RippleNode, ShockwaveNode,
                                       Transform3DNode, VHSNode)
from core.nodes.depth_generator_nodes import (CameraDepthNode,
                                              DepthGradientNode,
                                              DepthNoiseNode, DepthRampNode,
                                              DepthShapeNode,
                                              DisplacementMapNode,
                                              HeightMapNode,
                                              NormalFromDepthNode,
                                              NormalShapeNode, PositionMapNode,
                                              UVGridNode, UVSphereNode,
                                              VolumeNoiseNode, VolumeSliceNode)
from core.nodes.depth_nodes import (Anaglyph3DNode, DepthDisplaceNode,
                                    DepthEdgeNode, DepthHazeNode,
                                    DepthOfFieldNode, DepthParallaxNode,
                                    DepthRelightNode, DepthRimLightNode,
                                    DepthSliceNode, DepthTiltShiftNode,
                                    ZFogAdvancedNode, ZGlowAdvancedNode)
from core.nodes.distort_nodes import (BendNode, BulgeNode, BumpMapNode,
                                      DirectionalDisplaceNode, DisplaceNode,
                                      OffsetNode, TileNode, TwirlNode,
                                      WaveWarpNode)
from core.nodes.filter_effects import (DenoiseNode, EdgeDetectNode,
                                       GaussianBlurNode, MotionBlurNode,
                                       PixelateNode, SharpenNode, VignetteNode)
from core.nodes.generator_nodes import (CheckerboardNode, ColorBarsNode,
                                        FogNode, GradientNode,
                                        HeatDistortionNode, LensFlareNode,
                                        NoiseNode, RampNode, SolidColorNode,
                                        UVMapNode, VolumetricLightNode,
                                        ZFogNode)
from core.nodes.image_input import ImageInputNode
from core.nodes.keying_nodes import (ChromaKeyNode, CleanPlateNode,
                                     CombineMasksNode, DespillProNode,
                                     MatteEdgeNode, PremultNode,
                                     SpillSuppressNode)
from core.nodes.logic_nodes import (CompareNode, LogicGateNode, OscillatorNode,
                                    RandomNode, RangeCheckNode, SelectNode,
                                    SmoothStepNode)
from core.nodes.math_nodes import (ClampNode, MathFunctionNode, MathNode,
                                   PropertyDriveNode, PropertyLinkNode,
                                   RemapNode, ValueNode)
from core.nodes.roto_nodes import RotoNode
from core.nodes.smart_color_nodes import (AutoLevelsNode, AutoWhiteBalanceNode,
                                          ShotMatchNode)
from core.nodes.stylize_nodes import (BloomNode, FilmGrainNode, RadialBlurNode,
                                      ScanlinesNode)
from core.nodes.timing_nodes import (FilmFlickerNode, FrameHoldNode,
                                     PulseExposureNode, StrobeNode,
                                     TimeRemapNode)
from core.nodes.tracking_nodes import (PlanarHomographyTrackerNode,
                                       PlanarTrackerNode, SurfaceTrackerNode,
                                       TrackerNode)
from core.nodes.transform_nodes import (CornerPinMaskNode, CornerPinNode,
                                        CropNode, PerspectiveNode,
                                        PolarWarpNode, ShearNode,
                                        SphericalWarpNode, SwirlNode,
                                        Transform2DNode)
from core.nodes.utility_nodes import (ChannelMaskNode, FrameSwitchNode,
                                      InvertMaskNode)
from core.nodes.value_nodes import (TimelineFpsNode, TimelineFrameNode,
                                    TimelineMaxFrameNode,
                                    TimelineNormalizedNode, TimelineTimeNode)
from core.nodes.video_input import VideoInputNode
from core.nodes.viewer import ViewerNode

BUILTIN_NODE_TYPES: tuple[type[Node], ...] = (
    # Input / output
    VideoInputNode,
    ImageInputNode,
    ViewerNode,
    # Audio
    AudioExtractNode,
    AudioAttachNode,
    AudioGainNode,
    AudioMixNode,
    AudioAdvancedMixerNode,
    AudioDelayNode,
    AudioReverbNode,
    AudioEqNode,
    AudioPanNode,
    AudioCompressorNode,
    AudioLimiterNode,
    AudioGateNode,
    AudioNormalizeNode,
    AudioStereoWidthNode,
    AudioToMonoNode,
    # Generators
    SolidColorNode,
    GradientNode,
    CheckerboardNode,
    ColorBarsNode,
    RampNode,
    UVMapNode,
    LensFlareNode,
    HeatDistortionNode,
    FogNode,
    NoiseNode,
    VolumetricLightNode,
    ZFogNode,

    # Color
    ColorGradingNode,
    ExposureContrastNode,
    HueSaturationNode,
    WhiteBalanceNode,
    ChannelMixerNode,
    LevelsNode,
    VibranceNode,
    ShadowsHighlightsNode,
    ColorBalanceNode,
    ClarityNode,
    MonochromeNode,
    ThresholdNode,
    PosterizeNode,
    InvertNode,
    AutoLevelsNode,
    AutoWhiteBalanceNode,
    ShotMatchNode,
    # Filters
    GaussianBlurNode,
    SharpenNode,
    DenoiseNode,
    EdgeDetectNode,
    PixelateNode,
    VignetteNode,
    MotionBlurNode,
    # Compositing
    MergeNode,
    DissolveNode,
    AlphaOverNode,
    AlphaUnderNode,
    StencilNode,
    MatteCombineProNode,
    # Transform
    Transform2DNode,
    Transform3DNode,
    CropNode,
    CornerPinNode,
    CornerPinMaskNode,
    SphericalWarpNode,
    PolarWarpNode,
    SwirlNode,
    ShearNode,
    PerspectiveNode,
    # Creative
    KaleidoscopeNode,
    MirrorNode,
    LensDistortionNode,
    ChromaticAberrationNode,
    RGBSplitNode,
    GlitchNode,
    RippleNode,
    GlowNode,
    LightWrapNode,
    GlowEdgesNode,
    PosterEdgesNode,
    HalftoneNode,
    VHSNode,
    DuotoneNode,
    NeonGlowNode,
    PixelSortNode,
    ShockwaveNode,
    # Timing
    FilmFlickerNode,
    StrobeNode,
    PulseExposureNode,
    TimeRemapNode,
    FrameHoldNode,
    # Distort
    TwirlNode,
    BulgeNode,
    WaveWarpNode,
    TileNode,
    DisplaceNode,
    DirectionalDisplaceNode,
    BendNode,
    BumpMapNode,
    OffsetNode,
    # Effects / stylize
    FilmGrainNode,
    ScanlinesNode,
    BloomNode,
    RadialBlurNode,
    # Depth-based effects
    DepthDisplaceNode,
    DepthRimLightNode,
    DepthEdgeNode,
    DepthParallaxNode,
    DepthTiltShiftNode,
    ZFogAdvancedNode,
    ZGlowAdvancedNode,
    Anaglyph3DNode,
    DepthHazeNode,
    DepthOfFieldNode,
    DepthRelightNode,
    DepthSliceNode,
    # Depth-Generators
    DepthRampNode,
    DepthNoiseNode,
    DepthShapeNode,
    DepthGradientNode,
    NormalFromDepthNode,
    NormalShapeNode,
    PositionMapNode,
    CameraDepthNode,
    HeightMapNode,
    DisplacementMapNode,
    UVGridNode,
    UVSphereNode,
    VolumeNoiseNode,
    VolumeSliceNode,
    # Routing / keying utilities
    FrameSwitchNode,
    ChannelMaskNode,
    InvertMaskNode,
    ChromaKeyNode,
    SpillSuppressNode,
    MatteEdgeNode,
    CombineMasksNode,
    PremultNode,
    CleanPlateNode,
    DespillProNode,

    # Roto
    RotoNode,
    # Tracking
    TrackerNode,
    PlanarTrackerNode,
    # SurfaceTrackerNode,
    # PlanarHomographyTrackerNode,

    # Math / values
    ValueNode,
    TimelineFrameNode,
    TimelineTimeNode,
    TimelineFpsNode,
    TimelineMaxFrameNode,
    TimelineNormalizedNode,
    MathNode,
    MathFunctionNode,
    ClampNode,
    RemapNode,
    PropertyLinkNode,
    PropertyDriveNode,
    # Logic / procedural
    CompareNode,
    LogicGateNode,
    SelectNode,
    RangeCheckNode,
    SmoothStepNode,
    OscillatorNode,
    RandomNode,
)
