"""Stable enum values shared by built-in frame nodes."""

from __future__ import annotations

from enum import Enum, IntEnum, auto


class NoiseType(Enum):
    PERLIN = "perlin"
    SIMPLEX = "simplex"
    FBM = "fbm"

class VolumeSliceAxis(IntEnum):
    XY = auto()
    XZ = auto()
    YZ = auto()

class DepthRampMode(IntEnum):
    Horizontal = auto()
    Vertical = auto()
    Radial = auto()

class DepthShape(IntEnum):
    Sphere = auto()
    Box = auto()
    Cylinder = auto()

class ZMergeMode(IntEnum):
    Min = auto()
    Max = auto()
    Average = auto()

class BlendMode(IntEnum):
    """Pixel combination used by compositing nodes."""

    Normal = auto()
    Add = auto()
    Subtract = auto()
    Multiply = auto()
    Screen = auto()
    Overlay = auto()
    Difference = auto()
    Darken = auto()
    Lighten = auto()


class GradientMode(IntEnum):
    """Direction / shape of a generated gradient."""

    Horizontal = auto()
    Vertical = auto()
    Diagonal = auto()
    Radial = auto()


class TransformBorderMode(IntEnum):
    """Pixels synthesized beyond a transformed frame's bounds."""

    Black = auto()
    Hold = auto()
    Reflect = auto()


class SwitchInput(IntEnum):
    """Selected source for a two-input switch."""

    A = auto()
    B = auto()


class EdgeDisplayMode(IntEnum):
    """Presentation mode for detected edges."""

    Grayscale = auto()
    WhiteOnBlack = auto()
    BlackOnWhite = auto()


class BlurEdgeMode(IntEnum):
    """Border sampling policy for convolution and blur kernels."""

    Default = auto()
    Reflect = auto()
    Replicate = auto()
    Wrap = auto()


class MaskChannel(IntEnum):
    """Source channel used to generate a mask."""

    Luma = auto()
    Red = auto()
    Green = auto()
    Blue = auto()


class MirrorAxis(IntEnum):
    """Axis used by the mirror creative effect."""

    Horizontal = auto()
    Vertical = auto()


class CombineMaskMode(IntEnum):
    """Pixel operation used to combine two masks."""

    Add = auto()
    Subtract = auto()
    Intersect = auto()
    Max = auto()

class MatteCombineMode(IntEnum):
    """Pixel operation used to combine two mattes."""

    Add = auto()
    Subtract = auto()
    Multiply = auto()
    Max = auto()
    Min = auto()

class MathOperation(IntEnum):
    """Binary arithmetic operation for ``MathNode``."""

    Add = auto()
    Subtract = auto()
    Multiply = auto()
    Divide = auto()
    Power = auto()
    Minimum = auto()
    Maximum = auto()
    Average = auto()
    Modulo = auto()


class MathFunction(IntEnum):
    """Unary function for ``MathFunctionNode``."""

    Sine = auto()
    Cosine = auto()
    AbsoluteValue = auto()
    SquareRoot = auto()
    Negate = auto()
    Reciprocal = auto()


class ImageFitMode(IntEnum):
    """How a loaded still image is sized within its output frame."""

    Fit = auto()
    Fill = auto()
    Stretch = auto()
    Native = auto()


class ComparisonOperation(IntEnum):
    """Relational test applied by ``CompareNode`` to two numbers."""

    Greater = auto()
    GreaterOrEqual = auto()
    Less = auto()
    LessOrEqual = auto()
    Equal = auto()
    NotEqual = auto()


class LogicOperation(IntEnum):
    """Boolean combination applied by ``LogicGateNode`` to two numbers."""

    And = auto()
    Or = auto()
    ExclusiveOr = auto()
    Nand = auto()
    Nor = auto()
    NotA = auto()
    NotB = auto()


class Waveform(IntEnum):
    """Periodic shape generated by ``OscillatorNode``."""

    Sine = auto()
    Triangle = auto()
    Square = auto()
    Sawtooth = auto()
    Random = auto()


class DecodeQuality(IntEnum):
    """How much of the source resolution ``VideoInputNode`` decodes.

    This is the single most effective playback control for high-detail
    sources. Decoding 4K and then scaling down in software costs the full
    4K decode plus a full-frame scale; asking the decoder to emit the
    smaller frame costs a fraction of both, because the scaler runs inside
    the codec pipeline before the frame is ever materialised in memory.

    ``Auto`` follows the Viewer's preview width, which is what playback
    wants: never decode pixels the viewport cannot show.
    """

    #: Match the Viewer's preview width — never decode unseen pixels.
    Auto = auto()
    #: Full source resolution. Sharpest, and by far the most expensive.
    Full = auto()
    #: 3/4 resolution. Useful when zooming into a 4K source.
    High = auto()
    #: 1/2 resolution.
    Medium = auto()
    #: 1/3 resolution.
    Low = auto()
    #: 1/4 resolution. Cheapest fixed setting.
    Lowest = auto()


#: Resolution multiplier applied by each :class:`DecodeQuality` member.
#: ``None`` means "derive from the Viewer preview width".
DECODE_QUALITY_SCALE: dict["DecodeQuality", float | None] = {
    DecodeQuality.Auto: None,
    DecodeQuality.Full: 1.0,
    DecodeQuality.High: 0.75,
    DecodeQuality.Medium: 0.5,
    DecodeQuality.Low: 1.0 / 3.0,
    DecodeQuality.Lowest: 0.25,
}


class EaseMode(IntEnum):
    """Interpolation curve applied by ``SmoothStepNode``."""

    Linear = auto()
    SmoothStep = auto()
    SmootherStep = auto()
    EaseIn = auto()
    EaseOut = auto()
    EaseInOut = auto()


class BendAxis(IntEnum):
    """Orientation of the ``BendNode`` curvature."""

    Horizontal = auto()
    Vertical = auto()


class PixelSortMode(IntEnum):
    """Per-pixel sort key used by ``PixelSortNode``."""

    Luminance = auto()
    Hue = auto()
    Saturation = auto()


class AutoBalanceMode(IntEnum):
    """Statistical method used by ``AutoWhiteBalanceNode``."""

    GrayWorld = auto()
    WhitePatch = auto()


class AnaglyphMode(IntEnum):
    """Eyewear color pair produced by ``Anaglyph3DNode``."""

    RedCyan = auto()
    GreenMagenta = auto()
    AmberBlue = auto()


class TrackerShape(Enum):
    Ellipse = "ellipse"
    Rectangle = "rectangle"
    Polygon = "polygon"
