"""Stable enum values shared by built-in frame nodes."""

from __future__ import annotations

from enum import Enum, IntEnum, auto


class NoiseType(Enum):
    PERLIN = "perlin"
    SIMPLEX = "simplex"
    FBM = "fbm"

class VolumeSliceAxis(IntEnum):
    XY = auto()
    XZ = auto()
    YZ = auto()

class DepthRampMode(IntEnum):
    Horizontal = auto()
    Vertical = auto()
    Radial = auto()

class DepthShape(IntEnum):
    Sphere = auto()
    Box = auto()
    Cylinder = auto()

class ZMergeMode(IntEnum):
    Min = auto()
    Max = auto()
    Average = auto()

class BlendMode(IntEnum):
    """Pixel combination used by compositing nodes."""

    Normal = auto()
    Add = auto()
    Subtract = auto()
    Multiply = auto()
    Screen = auto()
    Overlay = auto()
    Difference = auto()
    Darken = auto()
    Lighten = auto()


class GradientMode(IntEnum):
    """Direction / shape of a generated gradient."""

    Horizontal = auto()
    Vertical = auto()
    Diagonal = auto()
    Radial = auto()


class TransformBorderMode(IntEnum):
    """Pixels synthesized beyond a transformed frame's bounds."""

    Black = auto()
    Hold = auto()
    Reflect = auto()


class SwitchInput(IntEnum):
    """Selected source for a two-input switch."""

    A = auto()
    B = auto()


class EdgeDisplayMode(IntEnum):
    """Presentation mode for detected edges."""

    Grayscale = auto()
    WhiteOnBlack = auto()
    BlackOnWhite = auto()


class BlurEdgeMode(IntEnum):
    """Border sampling policy for convolution and blur kernels."""

    Default = auto()
    Reflect = auto()
    Replicate = auto()
    Wrap = auto()


class MaskChannel(IntEnum):
    """Source channel used to generate a mask."""

    Luma = auto()
    Red = auto()
    Green = auto()
    Blue = auto()


class MirrorAxis(IntEnum):
    """Axis used by the mirror creative effect."""

    Horizontal = auto()
    Vertical = auto()


class CombineMaskMode(IntEnum):
    """Pixel operation used to combine two masks."""

    Add = auto()
    Subtract = auto()
    Intersect = auto()
    Max = auto()

class MatteCombineMode(IntEnum):
    """Pixel operation used to combine two mattes."""

    Add = auto()
    Subtract = auto()
    Multiply = auto()
    Max = auto()
    Min = auto()

class MathOperation(IntEnum):
    """Binary arithmetic operation for ``MathNode``."""

    Add = auto()
    Subtract = auto()
    Multiply = auto()
    Divide = auto()
    Power = auto()
    Minimum = auto()
    Maximum = auto()
    Average = auto()
    Modulo = auto()


class MathFunction(IntEnum):
    """Unary function for ``MathFunctionNode``."""

    Sine = auto()
    Cosine = auto()
    AbsoluteValue = auto()
    SquareRoot = auto()
    Negate = auto()
    Reciprocal = auto()


class ImageFitMode(IntEnum):
    """How a loaded still image is sized within its output frame."""

    Fit = auto()
    Fill = auto()
    Stretch = auto()
    Native = auto()


class ComparisonOperation(IntEnum):
    """Relational test applied by ``CompareNode`` to two numbers."""

    Greater = auto()
    GreaterOrEqual = auto()
    Less = auto()
    LessOrEqual = auto()
    Equal = auto()
    NotEqual = auto()


class LogicOperation(IntEnum):
    """Boolean combination applied by ``LogicGateNode`` to two numbers."""

    And = auto()
    Or = auto()
    ExclusiveOr = auto()
    Nand = auto()
    Nor = auto()
    NotA = auto()
    NotB = auto()


class Waveform(IntEnum):
    """Periodic shape generated by ``OscillatorNode``."""

    Sine = auto()
    Triangle = auto()
    Square = auto()
    Sawtooth = auto()
    Random = auto()


class EaseMode(IntEnum):
    """Interpolation curve applied by ``SmoothStepNode``."""

    Linear = auto()
    SmoothStep = auto()
    SmootherStep = auto()
    EaseIn = auto()
    EaseOut = auto()
    EaseInOut = auto()


class BendAxis(IntEnum):
    """Orientation of the ``BendNode`` curvature."""

    Horizontal = auto()
    Vertical = auto()


class PixelSortMode(IntEnum):
    """Per-pixel sort key used by ``PixelSortNode``."""

    Luminance = auto()
    Hue = auto()
    Saturation = auto()


class AutoBalanceMode(IntEnum):
    """Statistical method used by ``AutoWhiteBalanceNode``."""

    GrayWorld = auto()
    WhitePatch = auto()


class AnaglyphMode(IntEnum):
    """Eyewear color pair produced by ``Anaglyph3DNode``."""

    RedCyan = auto()
    GreenMagenta = auto()
    AmberBlue = auto()
